### PR TITLE
7.3.1

### PR DESCRIPTION
**Pull request by fcorneli**

### CODE REVIEW

**Comment by hasalex** [comment]
I cherry-pick the commit to avoid the useless merge commits.

**Comment by fcorneli** [comment]
I know... I'll try to create cleaner PRs in the future.

**Comment by fcorneli** [comment]
BTW: maybe this solution:
https://github.com/DanielWebelsiep/eap-build/commit/5492f2e10ddb19a87ea00d4a8bf1f568464a0731
is better.

**Comment by fcorneli** [comment]
jboss-eap-7.3.0-core-src.zip is actually version 10.1.2.Final-redhat-00001.
For 7.3.1 I'm using 10.0.3.Final.
I guess for 7.3.1 it would be better to also use jboss-eap-7.3.0-core-src.zip as done by https://github.com/DanielWebelsiep/eap-build/commit/5492f2e10ddb19a87ea00d4a8bf1f568464a0731

**Comment by hasalex** [comment]
I'm getting tired with all this mess between wifldfly and wildfly -core.

You're right, it would be better to have version 10.1.2.Final-redhat-00001.
I'll try to find a more generic solution based on Daniel's one.

**Pull request closed without merging**
