### PR TITLE
add 7.0.2

### PR DESCRIPTION
**Pull request by malys**

### CODE REVIEW

**Comment by hasalex** [comment]
Nice. But I'm convinced that switching back wildfly core to version 2.1.2.Final-redhat-1 is the best option. Did you try with the nearest public version, 2.1.8.Final ?

**Comment by malys** [comment]
Yes, I understand. But,I didn't find 2.1.8.Final artifact for wildfly-core-parent.
Morevover, only 2.1.2 contains wildfly-core-parent-XXXX-project-sources.tar.gz which is necessary to build  JBoss EAP.
I don't know very well Redhat maven repositories but I didn't find other solution... Any ideas!!!

**Comment by hasalex** [comment]
You're right. There's no 2.1.8.Final version. What a mess!

**Comment by hasalex** [comment]
I've tried to build with the public 2.2.0.Final version, but it fails.

**Comment by hasalex** [comment]
The new solution seems to be working. You may have a look to the eap7 branch.

**Comment by william-shuman** [comment]
Works for me.  Thanks for taking the time to do the refactor.

**Comment by malys** [comment]
Thank you for your feedback and refactoring.  I will validate your solution the next week and I will inform you.

**Comment by malys** [comment]
On Docker with  Centos 7, it failed.
```
    CORE_FULL_SOURCE_VERSION=$(grep "$CORE_VERSION=" src/jboss-eap-7.properties | cut -d '=' -f 2)
    CORE_FULL_SOURCE_VERSION=$(grep "$CORE_VERSION=" src/jboss-eap-7.properties | cut -d '=' -f 2 | tr -d '\n' )
```
maven isn't installed automatically ...
doble quote over some variables
patching not working...

I will investigate to solve some issues.

Bye and thank you for spending time on this new script release.

**Comment by hasalex** [comment]
Docker is a good idea... Could you move your comment to a separate issue, please ?

**Pull request closed without merging**
