### PR TITLE
Adding support for EAP versions 7.2.8, 7.2.9, and 7.3.10

### PR DESCRIPTION
**Pull request by georgesberscheid**

### CODE REVIEW

**Comment by Tokimimo** [comment]
This would be highly appreciated

**Comment by jarkkosonninen** [comment]
7.2.8 or 7.2.9 does not work for me
`
13:05:07,852 WARN  [org.jboss.modules.define] (MSC service thread 1-2) Failed to define class org.jboss.as.domain.http.server.ConsoleAvailabilityService in Module "org.jboss.as.domain-http-interface" version 6.0.30.Final-redhat-00001 from local module loader @79698539 (finder: local module finder @73f792cf (roots: /Users/jso/LT/jboss-eap-7.2.9/modules,/Users/jso/LT/jboss-eap-7.2.9/modules/system/layers/base)): java.lang.NoClassDefFoundError: Failed to link org/jboss/as/domain/http/server/ConsoleAvailabilityService (Module "org.jboss.as.domain-http-interface" version 6.0.30.Final-redhat-00001 from local module loader @79698539 (finder: local module finder @73f792cf (roots: /Users/jso/LT/jboss-eap-7.2.9/modules,/Users/jso/LT/jboss-eap-7.2.9/modules/system/layers/base))): org/jboss/msc/Service
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at org.jboss.modules.ModuleClassLoader.doDefineOrLoadClass(ModuleClassLoader.java:423)
	at org.jboss.modules.ModuleClassLoader.defineClass(ModuleClassLoader.java:519)
	at org.jboss.modules.ModuleClassLoader.loadClassLocal(ModuleClassLoader.java:339)
	at org.jboss.modules.ModuleClassLoader$1.loadClassLocal(ModuleClassLoader.java:126)
	at org.jboss.modules.Module.loadModuleClass(Module.java:731)
	at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:247)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:410)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:398)
	at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:116)
	at org.jboss.as.server.ApplicationServerService.start(ApplicationServerService.java:174)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1739)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.execute(ServiceControllerImpl.java:1701)
	at org.jboss.msc.service.ServiceControllerImpl$ControllerTask.run(ServiceControllerImpl.java:1559)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1982)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
	at java.lang.Thread.run(Thread.java:748)

13:05:07,853 ERROR [org.jboss.msc.service.fail] (MSC service thread 1-2) MSC000001: Failed to start service jboss.as: org.jboss.msc.service.StartException in service jboss.as: Failed to start service
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.execute(ServiceControllerImpl.java:1731)
	at org.jboss.msc.service.ServiceControllerImpl$ControllerTask.run(ServiceControllerImpl.java:1559)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1982)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoClassDefFoundError: Failed to link org/jboss/as/domain/http/server/ConsoleAvailabilityService (Module "org.jboss.as.domain-http-interface" version 6.0.30.Final-redhat-00001 from local module loader @79698539 (finder: local module finder @73f792cf (roots: /Users/jso/LT/jboss-eap-7.2.9/modules,/Users/jso/LT/jboss-eap-7.2.9/modules/system/layers/base))): org/jboss/msc/Service
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at org.jboss.modules.ModuleClassLoader.doDefineOrLoadClass(ModuleClassLoader.java:423)
	at org.jboss.modules.ModuleClassLoader.defineClass(ModuleClassLoader.java:519)
	at org.jboss.modules.ModuleClassLoader.loadClassLocal(ModuleClassLoader.java:339)
	at org.jboss.modules.ModuleClassLoader$1.loadClassLocal(ModuleClassLoader.java:126)
	at org.jboss.modules.Module.loadModuleClass(Module.java:731)
	at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:247)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:410)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:398)
	at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:116)
	at org.jboss.as.server.ApplicationServerService.start(ApplicationServerService.java:174)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1739)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.execute(ServiceControllerImpl.java:1701)
	... 6 more

java.util.concurrent.ExecutionException: JBTHR00005: Operation failed
	at org.jboss.threads.AsyncFutureTask.get(AsyncFutureTask.java:253)
	at org.jboss.as.server.Main.main(Main.java:109)
	at org.jboss.modules.Module.run(Module.java:352)
	at org.jboss.modules.Module.run(Module.java:320)
	at org.jboss.modules.Main.main(Main.java:593)
Caused by: org.jboss.msc.service.StartException in service jboss.as: Failed to start service
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.execute(ServiceControllerImpl.java:1731)
	at org.jboss.msc.service.ServiceControllerImpl$ControllerTask.run(ServiceControllerImpl.java:1559)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1982)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoClassDefFoundError: Failed to link org/jboss/as/domain/http/server/ConsoleAvailabilityService (Module "org.jboss.as.domain-http-interface" version 6.0.30.Final-redhat-00001 from local module loader @79698539 (finder: local module finder @73f792cf (roots: /Users/jso/LT/jboss-eap-7.2.9/modules,/Users/jso/LT/jboss-eap-7.2.9/modules/system/layers/base))): org/jboss/msc/Service
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at org.jboss.modules.ModuleClassLoader.doDefineOrLoadClass(ModuleClassLoader.java:423)
	at org.jboss.modules.ModuleClassLoader.defineClass(ModuleClassLoader.java:519)
	at org.jboss.modules.ModuleClassLoader.loadClassLocal(ModuleClassLoader.java:339)
	at org.jboss.modules.ModuleClassLoader$1.loadClassLocal(ModuleClassLoader.java:126)
	at org.jboss.modules.Module.loadModuleClass(Module.java:731)
	at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:247)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:410)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:398)
	at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:116)
	at org.jboss.as.server.ApplicationServerService.start(ApplicationServerService.java:174)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1739)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.execute(ServiceControllerImpl.java:1701)
	... 6 more
13:05:07,858 FATAL [org.jboss.as.server] (main) WFLYSRV0239: Aborting with exit code 1
`

**Comment by cher1705** [comment]
> 7.2.8 or 7.2.9 does not work for me
> 
> ```
> 13:05:07,852 WARN  [org.jboss.modules.define] (MSC service thread 1-2) Failed to define class org.jboss.as.domain.http.server.ConsoleAvailabilityService in Module "org.jboss.as.domain-http-interface" version 6.0.30.Final-redhat-00001 from local module loader @79698539 (finder: local module finder @73f792cf (roots: /Users/jso/LT/jboss-eap-7.2.9/modules,/Users/jso/LT/jboss-eap-7.2.9/modules/system/layers/base)): java.lang.NoClassDefFoundError: Failed to link org/jboss/as/domain/http/server/ConsoleAvailabilityService (Module "org.jboss.as.domain-http-interface" version 6.0.30.Final-redhat-00001 from local module loader @79698539 (finder: local module finder @73f792cf (roots: /Users/jso/LT/jboss-eap-7.2.9/modules,/Users/jso/LT/jboss-eap-7.2.9/modules/system/layers/base))): org/jboss/msc/Service
> 	at java.lang.ClassLoader.defineClass1(Native Method)
> 	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
> 	at org.jboss.modules.ModuleClassLoader.doDefineOrLoadClass(ModuleClassLoader.java:423)
> 	at org.jboss.modules.ModuleClassLoader.defineClass(ModuleClassLoader.java:519)
> 	at org.jboss.modules.ModuleClassLoader.loadClassLocal(ModuleClassLoader.java:339)
> 	at org.jboss.modules.ModuleClassLoader$1.loadClassLocal(ModuleClassLoader.java:126)
> 	at org.jboss.modules.Module.loadModuleClass(Module.java:731)
> 	at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:247)
> 	at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:410)
> 	at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:398)
> 	at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:116)
> 	at org.jboss.as.server.ApplicationServerService.start(ApplicationServerService.java:174)
> 	at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1739)
> 	at org.jboss.msc.service.ServiceControllerImpl$StartTask.execute(ServiceControllerImpl.java:1701)
> 	at org.jboss.msc.service.ServiceControllerImpl$ControllerTask.run(ServiceControllerImpl.java:1559)
> 	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
> 	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1982)
> 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
> 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
> 	at java.lang.Thread.run(Thread.java:748)
> 
> 13:05:07,853 ERROR [org.jboss.msc.service.fail] (MSC service thread 1-2) MSC000001: Failed to start service jboss.as: org.jboss.msc.service.StartException in service jboss.as: Failed to start service
> 	at org.jboss.msc.service.ServiceControllerImpl$StartTask.execute(ServiceControllerImpl.java:1731)
> 	at org.jboss.msc.service.ServiceControllerImpl$ControllerTask.run(ServiceControllerImpl.java:1559)
> 	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
> 	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1982)
> 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
> 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
> 	at java.lang.Thread.run(Thread.java:748)
> Caused by: java.lang.NoClassDefFoundError: Failed to link org/jboss/as/domain/http/server/ConsoleAvailabilityService (Module "org.jboss.as.domain-http-interface" version 6.0.30.Final-redhat-00001 from local module loader @79698539 (finder: local module finder @73f792cf (roots: /Users/jso/LT/jboss-eap-7.2.9/modules,/Users/jso/LT/jboss-eap-7.2.9/modules/system/layers/base))): org/jboss/msc/Service
> 	at java.lang.ClassLoader.defineClass1(Native Method)
> 	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
> 	at org.jboss.modules.ModuleClassLoader.doDefineOrLoadClass(ModuleClassLoader.java:423)
> 	at org.jboss.modules.ModuleClassLoader.defineClass(ModuleClassLoader.java:519)
> 	at org.jboss.modules.ModuleClassLoader.loadClassLocal(ModuleClassLoader.java:339)
> 	at org.jboss.modules.ModuleClassLoader$1.loadClassLocal(ModuleClassLoader.java:126)
> 	at org.jboss.modules.Module.loadModuleClass(Module.java:731)
> 	at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:247)
> 	at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:410)
> 	at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:398)
> 	at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:116)
> 	at org.jboss.as.server.ApplicationServerService.start(ApplicationServerService.java:174)
> 	at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1739)
> 	at org.jboss.msc.service.ServiceControllerImpl$StartTask.execute(ServiceControllerImpl.java:1701)
> 	... 6 more
> 
> java.util.concurrent.ExecutionException: JBTHR00005: Operation failed
> 	at org.jboss.threads.AsyncFutureTask.get(AsyncFutureTask.java:253)
> 	at org.jboss.as.server.Main.main(Main.java:109)
> 	at org.jboss.modules.Module.run(Module.java:352)
> 	at org.jboss.modules.Module.run(Module.java:320)
> 	at org.jboss.modules.Main.main(Main.java:593)
> Caused by: org.jboss.msc.service.StartException in service jboss.as: Failed to start service
> 	at org.jboss.msc.service.ServiceControllerImpl$StartTask.execute(ServiceControllerImpl.java:1731)
> 	at org.jboss.msc.service.ServiceControllerImpl$ControllerTask.run(ServiceControllerImpl.java:1559)
> 	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
> 	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1982)
> 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
> 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
> 	at java.lang.Thread.run(Thread.java:748)
> Caused by: java.lang.NoClassDefFoundError: Failed to link org/jboss/as/domain/http/server/ConsoleAvailabilityService (Module "org.jboss.as.domain-http-interface" version 6.0.30.Final-redhat-00001 from local module loader @79698539 (finder: local module finder @73f792cf (roots: /Users/jso/LT/jboss-eap-7.2.9/modules,/Users/jso/LT/jboss-eap-7.2.9/modules/system/layers/base))): org/jboss/msc/Service
> 	at java.lang.ClassLoader.defineClass1(Native Method)
> 	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
> 	at org.jboss.modules.ModuleClassLoader.doDefineOrLoadClass(ModuleClassLoader.java:423)
> 	at org.jboss.modules.ModuleClassLoader.defineClass(ModuleClassLoader.java:519)
> 	at org.jboss.modules.ModuleClassLoader.loadClassLocal(ModuleClassLoader.java:339)
> 	at org.jboss.modules.ModuleClassLoader$1.loadClassLocal(ModuleClassLoader.java:126)
> 	at org.jboss.modules.Module.loadModuleClass(Module.java:731)
> 	at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:247)
> 	at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:410)
> 	at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:398)
> 	at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:116)
> 	at org.jboss.as.server.ApplicationServerService.start(ApplicationServerService.java:174)
> 	at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1739)
> 	at org.jboss.msc.service.ServiceControllerImpl$StartTask.execute(ServiceControllerImpl.java:1701)
> 	... 6 more
> 13:05:07,858 FATAL [org.jboss.as.server] (main) WFLYSRV0239: Aborting with exit code 1
> ```

Already done or still problems?

**Comment by cher1705** [comment]
@georgesberscheid
please resolve conflicts..
please build a jboss like 7.2.8 again. if you get an error, look at the used mvn repo...
I changed MAVEN_REPO to use https://maven.repository.redhat.com/ga instead of the earlyaccess site

**Comment by jarkkosonninen** [comment]
7.2.8 gives the same error.

**Comment by georgesberscheid** [comment]
Will restart from scratch :-)

**Comment by cher1705** [comment]
> 7.2.8 gives the same error.

what, if you add
7.2.8.xpath.delete.core=feature-pack-build.xml,//_:copy-artifact[@artifact='org.wildfly.openssl:wildfly-openssl-macosx-x86_64']
7.2.8.xpath.insert.core=src/main/resources/modules/system/layers/base/org/jboss/as/domain-http-interface/main/module.xml,/_:module/_:dependencies/_:module[position()=1],module,name="org.jboss.msc"
7.2.8.xpath.insert.core=src/main/resources/modules/system/layers/base/org/jboss/as/domain-http-interface/main/module.xml,/_:module/_:dependencies/_:module[position()=1],module,name="java.desktop"

@georgesberscheid 
if this works for @jarkkosonninen please add those lines also

**Comment by jarkkosonninen** [comment]
Thanks, it seem to work now, after adding some underscores to the xpaths. The diff would be 
```
diff --git a/readme.md b/readme.md
index 8f9e65d..ee56d87 100644
--- a/readme.md
+++ b/readme.md
@@ -43,7 +43,7 @@ If you don't want to use git, download the archive, unzip it and run the main sc
 
 Versions
 --------
-The build-eap7.sh script supports 7.0.0->7.0.9, 7.1.0->7.1.4, 7.2.0->7.2.7, 7.3.0->7.3.9, 7.4.0->7.4.3.
+The build-eap7.sh script supports 7.0.0->7.0.9, 7.1.0->7.1.4, 7.2.0->7.2.9, 7.3.0->7.3.9, 7.4.0->7.4.3.
 
 The build-eap6.sh script supports 6.1.1, 6.2.0->6.2.4, 6.3.0->6.3.3, 6.4.0->6.4.23.
 
diff --git a/src/functions-7.sh b/src/functions-7.sh
index 32a9468..b874ffa 100755
--- a/src/functions-7.sh
+++ b/src/functions-7.sh
@@ -50,7 +50,7 @@ function prepare_core_source {
 
         cd $BUILD_HOME/work/wildfly-core-$CORE_VERSION/core-feature-pack
     else
-        MAVEN_REPO=https://maven.repository.redhat.com/earlyaccess
+        MAVEN_REPO=https://maven.repository.redhat.com/ga
         if [[ $CORE_FULL_SOURCE_VERSION = *"-redhat-"* ]]
         then
             download_and_unzip $MAVEN_REPO/org/wildfly/core/wildfly-core-parent/$CORE_FULL_SOURCE_VERSION/wildfly-core-parent-$CORE_FULL_SOURCE_VERSION-project-sources.tar.gz
diff --git a/src/jboss-eap-7.properties b/src/jboss-eap-7.properties
index ae81ae6..a763731 100644
--- a/src/jboss-eap-7.properties
+++ b/src/jboss-eap-7.properties
@@ -1,4 +1,4 @@
-versions=7.0.0,7.0.1,7.0.2,7.0.3,7.0.4,7.0.5,7.0.6,7.0.7,7.0.8,7.0.9,7.1.0,7.1.1,7.1.2,7.1.3,7.1.4,7.2.0,7.2.1,7.2.2,7.2.3,7.2.4,7.2.5,7.2.6,7.2.7,7.3.0,7.3.1,7.3.2,7.3.3,7.3.4,7.3.5,7.3.6,7.3.7,7.3.8,7.3.9,7.4.0,7.4.1,7.4.2,7.4.3
+versions=7.0.0,7.0.1,7.0.2,7.0.3,7.0.4,7.0.5,7.0.6,7.0.7,7.0.8,7.0.9,7.1.0,7.1.1,7.1.2,7.1.3,7.1.4,7.2.0,7.2.1,7.2.2,7.2.3,7.2.4,7.2.5,7.2.6,7.2.7,7.2.8,7.2.9,7.3.0,7.3.1,7.3.2,7.3.3,7.3.4,7.3.5,7.3.6,7.3.7,7.3.8,7.3.9,7.4.0,7.4.1,7.4.2,7.4.3
 
 # core version and corresponding version with full source code
 # EAP 7.0.0
@@ -50,6 +50,10 @@ versions=7.0.0,7.0.1,7.0.2,7.0.3,7.0.4,7.0.5,7.0.6,7.0.7,7.0.8,7.0.9,7.1.0,7.1.1
 6.0.21.Final-redhat-00001=6.0.2.Final
 # EAP 7.2.7
 6.0.24.Final-redhat-00001=6.0.2.Final
+# EAP 7.2.8
+6.0.27.Final-redhat-00001=6.0.2.Final
+# EAP 7.2.9
+6.0.30.Final-redhat-00001=6.0.2.Final
 # EAP 7.3.0 : direct download of the core source file
 # EAP 7.3.1
 10.1.7.Final-redhat-00001=10.0.3.Final
@@ -126,6 +130,12 @@ versions=7.0.0,7.0.1,7.0.2,7.0.3,7.0.4,7.0.5,7.0.6,7.0.7,7.0.8,7.0.9,7.1.0,7.1.1
 7.2.5.xpath.delete.core=feature-pack-build.xml,//_:copy-artifact[@artifact='org.wildfly.openssl:wildfly-openssl-macosx-x86_64']
 7.2.6.xpath.delete.core=feature-pack-build.xml,//_:copy-artifact[@artifact='org.wildfly.openssl:wildfly-openssl-macosx-x86_64']
 7.2.7.xpath.delete.core=feature-pack-build.xml,//_:copy-artifact[@artifact='org.wildfly.openssl:wildfly-openssl-macosx-x86_64']
+7.2.8.xpath.delete.core=feature-pack-build.xml,//_:copy-artifact[@artifact='org.wildfly.openssl:wildfly-openssl-macosx-x86_64']
+7.2.8.xpath.insert.core=src/main/resources/modules/system/layers/base/org/jboss/as/domain-http-interface/main/module.xml,/_:module/_:dependencies/_:module[position()=1],module,name="org.jboss.msc"
+7.2.8.xpath.insert.core=src/main/resources/modules/system/layers/base/org/jboss/as/domain-http-interface/main/module.xml,/_:module/_:dependencies/_:module[position()=1],module,name="java.desktop"
+7.2.9.xpath.delete.core=feature-pack-build.xml,//_:copy-artifact[@artifact='org.wildfly.openssl:wildfly-openssl-macosx-x86_64']
+7.2.9.xpath.insert.core=src/main/resources/modules/system/layers/base/org/jboss/as/domain-http-interface/main/module.xml,/_:module/_:dependencies/_:module[position()=1],module,name="org.jboss.msc"
+7.2.9.xpath.insert.core=src/main/resources/modules/system/layers/base/org/jboss/as/domain-http-interface/main/module.xml,/_:module/_:dependencies/_:module[position()=1],module,name="java.desktop"
 # 
 7.3.0.xpath.delete.core=pom.xml,//_:dependency[_:artifactId='wildfly-core-model-test-framework']
 7.3.1.xpath.delete.core=feature-pack-build.xml,//_:copy-artifact[@artifact='org.wildfly.openssl:wildfly-openssl-macosx-x86_64']
```

**Pull request closed without merging**
