### PR TITLE
Version 7.4.1 (#165)

### PR DESCRIPTION
**Pull request by hasalex**
Hi @cher1705 ,

Could make a review of this PR ? 
And maybe test it ?

Thanks,
Alexis

### CODE REVIEW

**Review by cher1705 — APPROVED** [review]
I was able to build 7.4.1 and also 7.4.2 which is the brand new version...
THANKS also to @LPETERS006, he was the first one with skipping tests...

I think we have to go this way. RH will not upload missing deps to their public mvn repo.

> Some of the internal dependency jars that ... requires at build time are not available with the Red Hat internal version numbers on a publicly available maven repository
I have found this answer in RH knowledge base for RH-SSO. Also if you look at the README files of the sources, you will find sth like "to build blabla, you have to be connected via VPN to RH, to get access to their internal mvn repo....

**Comment by cher1705** [comment]
Are you using 7.4.x?
How much effort took it, to migrate your app from 7.3.x to 7.4.x?

**Comment by hasalex** [comment]
Thank you, @cher1705, that's a good news.

I merge the PR. 
Would you like to make an other one for version 7.4.2 ?

**Comment by fcorneli** [comment]
@cher1705 I could run two rather big Java EE apps on 7.4.1 without any change (only noticeable difference in the occasional version bumping within the `urn:jboss:domain:...` configuration namespaces). Hence seems like you don't really have to "migrate" your app going from 7.3 to 7.4.

**Pull request merged**
